
-- Global International Banking Database Schema
-- Optimized for Supabase (PostgreSQL)

-- 1. Profiles Table
-- Stores institutional account information and current liquidity balance
-- This table should be linked to Supabase Auth users
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    role TEXT CHECK (role IN ('admin', 'user')) DEFAULT 'user',
    balance DECIMAL(20, 2) DEFAULT 0.00,
    currency TEXT DEFAULT 'USD',
    bank_entity TEXT,
    swift_code TEXT,
    iban TEXT,
    account_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Transactions Table
-- Stores all clearing and settlement records
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    name TEXT NOT NULL,
    recipient_name TEXT,
    amount TEXT NOT NULL, -- Stored as string to preserve formatting/precision if needed
    currency TEXT NOT NULL,
    type TEXT CHECK (type IN ('in', 'out')),
    status TEXT NOT NULL,
    reference_id TEXT UNIQUE NOT NULL,
    recipient_iban TEXT,
    bic TEXT,
    payment_reason TEXT,
    is_sepa BOOLEAN DEFAULT false,
    timeframe TEXT,
    utr TEXT,
    fee TEXT,
    total_settlement TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Recipients Table
-- Address book for institutional transfers
CREATE TABLE IF NOT EXISTS recipients (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    name TEXT NOT NULL,
    iban TEXT NOT NULL,
    bic TEXT NOT NULL,
    account_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Disputes Table
CREATE TABLE IF NOT EXISTS disputes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    reason TEXT NOT NULL,
    details TEXT,
    status TEXT CHECK (status IN ('pending', 'under_review', 'resolved', 'rejected')) DEFAULT 'pending',
    resolution_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipients ENABLE ROW LEVEL SECURITY;
ALTER TABLE disputes ENABLE ROW LEVEL SECURITY;

-- 6. Basic RLS Policies
-- Profiles
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update all profiles" ON profiles FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Transactions
CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all transactions" ON transactions FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Recipients
CREATE POLICY "Users can manage own recipients" ON recipients FOR ALL USING (auth.uid() = user_id);

-- Disputes
CREATE POLICY "Users can view own disputes" ON disputes FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own disputes" ON disputes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all disputes" ON disputes FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update all disputes" ON disputes FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
